### ISSUE TITLE
[Milestone ] - Update Repo

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/data-science-workflows#25]
Some of the content and organization of this repository has gone a bit stale. Since this work is being promoted on the Operate-First site we should make sure that all the content is up to date and its all reasonably organized. 

Acceptance Criteria:

- [x] Ensure all content is up to date 
- [x] Re Organize content for ease of discovery

**Comment by amsaparov** [comment]
I think it would be helpful to create a similar overview page (like AI for CI has) with a text blurb that can be taken from/a modified version of what’s on the google doc (https://docs.google.com/document/d/1LqVXQbd81IdPfoXw2B0iCcnb-ygCVvdy_8vejY08zZ4/edit). And at the bottom links could be included to Get Started, Project Template, and Guidelines for Reviewing. Then, what is currently the overview could potentially become the Get Started (or it could remain on the overview page under the text blurb). 
@MichaelClifford @aakankshaduggal

**Comment by MichaelClifford** [comment]
:+1:  Sounds great @amsaparov !

**Comment by amsaparov** [comment]
I also noticed that the current overview/get started has a lot of links which is a bit overwhelming if I am just trying to get started, and some of the links appear to lead to the same documentation but in different locations (Template doc leads to google doc which appears to be the same as the project template linked on the website. So I think it would likely be helpful if it was just linked directly to the website one. I also think the example template link could potentially be linked on the template documentation rather than within the overview.
